apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  project: lab
  source:
    repoURL: https://github.com/iars13/argocd_lab.git
    targetRevision: main
    path: helm/nginx
    helm:
      valueFiles:
        - values.yaml
        - environment/integracion-helm/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: integracion-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
